using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Perfect_Freight_Manager.Models
{
    public class MaintenanceTruckTipoII
    {
        public int id { get; set; }
        public string truckid { get; set; }
        public string milestotal { get; set; }
        public string dateinitial { get; set; }
        public string dateend { get; set; }
        public string drivername { get; set; }
        public string prt1 { get; set; }
        public string pot1 { get; set; }
        public string rr1 { get; set; }
        public string prt2 { get; set; }
        public string pot2 { get; set; }
        public string rr2 { get; set; }
        public string prt3 { get; set; }
        public string pot3 { get; set; }
        public string rr3 { get; set; }
        public string prt4 { get; set; }
        public string pot4 { get; set; }
        public string rr4 { get; set; }
        public string prt5 { get; set; }
        public string pot5 { get; set; }
        public string rr5 { get; set; }
        public string prt6 { get; set; }
        public string pot6 { get; set; }
        public string rr6 { get; set; }
        public string prt7 { get; set; }
        public string pot7 { get; set; }
        public string rr7 { get; set; }
        public string prt8 { get; set; }
        public string pot8 { get; set; }
        public string rr8 { get; set; }
        public string prt9 { get; set; }
        public string pot9 { get; set; }
        public string rr9 { get; set; }
        public string prt10 { get; set; }
        public string pot10 { get; set; }
        public string rr10 { get; set; }
        public string prt11 { get; set; }
        public string pot11 { get; set; }
        public string rr11 { get; set; }
        public string prt12 { get; set; }
        public string pot12 { get; set; }
        public string rr12 { get; set; }
        public string prt13 { get; set; }
        public string pot13 { get; set; }
        public string rr13 { get; set; }
        public string prt14 { get; set; }
        public string pot14 { get; set; }
        public string rr14 { get; set; }
        public string prt15 { get; set; }
        public string pot15 { get; set; }
        public string rr15 { get; set; }
        public string prt16 { get; set; }
        public string pot16 { get; set; }
        public string rr16 { get; set; }
        public string prt17 { get; set; }
        public string pot17 { get; set; }
        public string rr17 { get; set; }
        public string prt18 { get; set; }
        public string pot18 { get; set; }
        public string rr18 { get; set; }
        public string prt19 { get; set; }
        public string pot19 { get; set; }
        public string rr19 { get; set; }
        public string prt20 { get; set; }
        public string pot20 { get; set; }
        public string rr20 { get; set; }
        public string prt21 { get; set; }
        public string pot21 { get; set; }
        public string rr21 { get; set; }
        public string prt22 { get; set; }
        public string pot22 { get; set; }
        public string rr22 { get; set; }
        public string prt23 { get; set; }
        public string pot23 { get; set; }
        public string rr23 { get; set; }
        public string prt24 { get; set; }
        public string pot24 { get; set; }
        public string rr24 { get; set; }
        public string prt25 { get; set; }
        public string pot25 { get; set; }
        public string rr25 { get; set; }
        public string prt26 { get; set; }
        public string pot26 { get; set; }
        public string rr26 { get; set; }
        public string prt27 { get; set; }
        public string pot27 { get; set; }
        public string rr27 { get; set; }
        public string prt28 { get; set; }
        public string pot28 { get; set; }
        public string rr28 { get; set; }
        public string prt29 { get; set; }
        public string pot29 { get; set; }
        public string rr29 { get; set; }
        public string prt30 { get; set; }
        public string pot30 { get; set; }
        public string rr30 { get; set; }
        public string prt31 { get; set; }
        public string pot31 { get; set; }
        public string rr31 { get; set; }
        public string prt32 { get; set; }
        public string pot32 { get; set; }
        public string rr32 { get; set; }
        public string prt33 { get; set; }
        public string pot33 { get; set; }
        public string rr33 { get; set; }
        public string prt34 { get; set; }
        public string pot34 { get; set; }
        public string rr34 { get; set; }
        public string prt35 { get; set; }
        public string pot35 { get; set; }
        public string rr35 { get; set; }
        public string prt36 { get; set; }
        public string pot36 { get; set; }
        public string rr36 { get; set; }
        public string prt37 { get; set; }
        public string pot37 { get; set; }
        public string rr37 { get; set; }
        public string prt38 { get; set; }
        public string pot38 { get; set; }
        public string rr38 { get; set; }
        public string prt39 { get; set; }
        public string pot39 { get; set; }
        public string rr39 { get; set; }
        public string prt40 { get; set; }
        public string pot40 { get; set; }
        public string rr40 { get; set; }
        public string prt41 { get; set; }
        public string pot41 { get; set; }
        public string rr41 { get; set; }
        public string prt42 { get; set; }
        public string pot42 { get; set; }
        public string rr42 { get; set; }
        public string prt43 { get; set; }
        public string pot43 { get; set; }
        public string rr43 { get; set; }
        public string prt44 { get; set; }
        public string pot44 { get; set; }
        public string rr44 { get; set; }
        public string prt45 { get; set; }
        public string pot45 { get; set; }
        public string rr45 { get; set; }
        public string prt46 { get; set; }
        public string pot46 { get; set; }
        public string rr46 { get; set; }
        public string prt47 { get; set; }
        public string pot47 { get; set; }
        public string rr47 { get; set; }
        public string prt48 { get; set; }
        public string pot48 { get; set; }
        public string rr48 { get; set; }
        public string prt49 { get; set; }
        public string pot49 { get; set; }
        public string rr49 { get; set; }
        public string prt50 { get; set; }
        public string pot50 { get; set; }
        public string rr50 { get; set; }
        public string prt51 { get; set; }
        public string pot51 { get; set; }
        public string rr51 { get; set; }
        public string prt52 { get; set; }
        public string pot52 { get; set; }
        public string rr52 { get; set; }
        public string prt53 { get; set; }
        public string pot53 { get; set; }
        public string rr53 { get; set; }
        public string prt54 { get; set; }
        public string pot54 { get; set; }
        public string rr54 { get; set; }
        public string prt55 { get; set; }
        public string pot55 { get; set; }
        public string rr55 { get; set; }
        public string prt56 { get; set; }
        public string pot56 { get; set; }
        public string rr56 { get; set; }
        public string prt57 { get; set; }
        public string pot57 { get; set; }
        public string rr57 { get; set; }
        public string prt58 { get; set; }
        public string pot58 { get; set; }
        public string rr58 { get; set; }
        public string prt59 { get; set; }
        public string pot59 { get; set; }
        public string rr59 { get; set; }
        public string prt60 { get; set; }
        public string pot60 { get; set; }
        public string rr60 { get; set; }
        public string prt61 { get; set; }
        public string pot61 { get; set; }
        public string rr61 { get; set; }
        public string prt62 { get; set; }
        public string pot62 { get; set; }
        public string rr62 { get; set; }
        public string prt63 { get; set; }
        public string pot63 { get; set; }
        public string rr63 { get; set; }
        public string prt64 { get; set; }
        public string pot64 { get; set; }
        public string rr64 { get; set; }
        public string notes { get; set; }
        public string numberorder { get; set; }
        public string statusorder { get; set; }
    }
}
