using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Perfect_Freight_Manager.Models
{
    public class MaintenanceTrailer
    {
        public int id { get; set; }
        public string trailerid { get; set; }
        public string milestotal { get; set; }
        public string dateinitial { get; set; }
        public string dateend { get; set; }
        public string drivername { get; set; }
        public string inok1 { get; set; }
        public string inok2 { get; set; }
        public string inok3 { get; set; }
        public string inok4 { get; set; }
        public string inok5 { get; set; }
        public string innr1 { get; set; }
        public string innr2 { get; set; }
        public string innr3 { get; set; }
        public string innr4 { get; set; }
        public string innr5 { get; set; }
        public string outok1 { get; set; }
        public string outok2 { get; set; }
        public string outok3 { get; set; }
        public string outok4 { get; set; }
        public string outok5 { get; set; }
        public string outnr1 { get; set; }
        public string outnr2 { get; set; }
        public string outnr3 { get; set; }
        public string outnr4 { get; set; }
        public string outnr5 { get; set; }
        public string inok6 { get; set; }
        public string inok7 { get; set; }
        public string inok8 { get; set; }
        public string inok9 { get; set; }
        public string inok10 { get; set; }
        public string inok11 { get; set; }
        public string inok12 { get; set; }
        public string innr6 { get; set; }
        public string innr7 { get; set; }
        public string innr8 { get; set; }
        public string innr9 { get; set; }
        public string innr10 { get; set; }
        public string innr11 { get; set; }
        public string innr12 { get; set; }
        public string outok6 { get; set; }
        public string outok7 { get; set; }
        public string outok8 { get; set; }
        public string outok9 { get; set; }
        public string outok10 { get; set; }
        public string outok11 { get; set; }
        public string outok12 { get; set; }
        public string outnr6 { get; set; }
        public string outnr7 { get; set; }
        public string outnr8 { get; set; }
        public string outnr9 { get; set; }
        public string outnr10 { get; set; }
        public string outnr11 { get; set; }
        public string outnr12 { get; set; }
        public string inok13 { get; set; }
        public string inok14 { get; set; }
        public string inok15 { get; set; }
        public string inok16 { get; set; }
        public string inok17 { get; set; }
        public string inok18 { get; set; }
        public string inok19 { get; set; }
        public string innr13 { get; set; }
        public string innr14 { get; set; }
        public string innr15 { get; set; }
        public string innr16 { get; set; }
        public string innr17 { get; set; }
        public string innr18 { get; set; }
        public string innr19 { get; set; }
        public string outok13 { get; set; }
        public string outok14 { get; set; }
        public string outok15 { get; set; }
        public string outok16 { get; set; }
        public string outok17 { get; set; }
        public string outok18 { get; set; }
        public string outok19 { get; set; }
        public string outnr13 { get; set; }
        public string outnr14 { get; set; }
        public string outnr15 { get; set; }
        public string outnr16 { get; set; }
        public string outnr17 { get; set; }
        public string outnr18 { get; set; }
        public string outnr19 { get; set; }
        public string inok20 { get; set; }
        public string inok21 { get; set; }
        public string inok22 { get; set; }
        public string inok23 { get; set; }
        public string inok24 { get; set; }
        public string innr20 { get; set; }
        public string innr21 { get; set; }
        public string innr22 { get; set; }
        public string innr23 { get; set; }
        public string innr24 { get; set; }
        public string outok20 { get; set; }
        public string outok21 { get; set; }
        public string outok22 { get; set; }
        public string outok23 { get; set; }
        public string outok24 { get; set; }
        public string outnr20 { get; set; }
        public string outnr21 { get; set; }
        public string outnr22 { get; set; }
        public string outnr23 { get; set; }
        public string outnr24 { get; set; }
        public string inok25 { get; set; }
        public string inok26 { get; set; }
        public string inok27 { get; set; }
        public string inok28 { get; set; }
        public string inok29 { get; set; }
        public string inok30 { get; set; }
        public string inok31 { get; set; }
        public string innr25 { get; set; }
        public string innr26 { get; set; }
        public string innr27 { get; set; }
        public string innr28 { get; set; }
        public string innr29 { get; set; }
        public string innr30 { get; set; }
        public string innr31 { get; set; }
        public string outok25 { get; set; }
        public string outok26 { get; set; }
        public string outok27 { get; set; }
        public string outok28 { get; set; }
        public string outok29 { get; set; }
        public string outok30 { get; set; }
        public string outok31 { get; set; }
        public string outnr25 { get; set; }
        public string outnr26 { get; set; }
        public string outnr27 { get; set; }
        public string outnr28 { get; set; }
        public string outnr29 { get; set; }
        public string outnr30 { get; set; }
        public string outnr31 { get; set; }
        public string inok32 { get; set; }
        public string inok33 { get; set; }
        public string inok34 { get; set; }
        public string inok35 { get; set; }
        public string inok36 { get; set; }
        public string inok37 { get; set; }
        public string inok38 { get; set; }
        public string innr32 { get; set; }
        public string innr33 { get; set; }
        public string innr34 { get; set; }
        public string innr35 { get; set; }
        public string innr36 { get; set; }
        public string innr37 { get; set; }
        public string innr38 { get; set; }
        public string outok32 { get; set; }
        public string outok33 { get; set; }
        public string outok34 { get; set; }
        public string outok35 { get; set; }
        public string outok36 { get; set; }
        public string outok37 { get; set; }
        public string outok38 { get; set; }
        public string outnr32 { get; set; }
        public string outnr33 { get; set; }
        public string outnr34 { get; set; }
        public string outnr35 { get; set; }
        public string outnr36 { get; set; }
        public string outnr37 { get; set; }
        public string outnr38 { get; set; }


        public string inok39 { get; set; }
        public string inok40 { get; set; }
        public string inok41 { get; set; }
        public string inok42 { get; set; }
        public string inok43 { get; set; }
        public string innr39 { get; set; }
        public string innr40 { get; set; }
        public string innr41 { get; set; }
        public string innr42 { get; set; }
        public string innr43 { get; set; }
        public string outok39 { get; set; }
        public string outok40 { get; set; }
        public string outok41 { get; set; }
        public string outok42 { get; set; }
        public string outok43 { get; set; }
        public string outnr39 { get; set; }
        public string outnr40 { get; set; }
        public string outnr41 { get; set; }
        public string outnr42 { get; set; }
        public string outnr43 { get; set; }
        public string inok44 { get; set; }
        public string inok45 { get; set; }
        public string inok46 { get; set; }
        public string inok47 { get; set; }
        public string inok48 { get; set; }
        public string innr44 { get; set; }
        public string innr45 { get; set; }
        public string innr46 { get; set; }
        public string innr47 { get; set; }
        public string innr48 { get; set; }
        public string outok44 { get; set; }
        public string outok45 { get; set; }
        public string outok46 { get; set; }
        public string outok47 { get; set; }
        public string outok48 { get; set; }
        public string outnr44 { get; set; }
        public string outnr45 { get; set; }
        public string outnr46 { get; set; }
        public string outnr47 { get; set; }
        public string outnr48 { get; set; }
        public string notes { get; set; }
        public string numberorder { get; set; }
        public string statusorder { get; set; }
    }
}
